#!/usr/bin/env python3

######################################################
# Slippy Assignment
######################################################

import sys
from args_parser import ArgsParser
from sed_parser import SedParser

######################################################
# Parse arguments
######################################################

args_parser = ArgsParser(sys.argv[1:])

commands = SedParser(args_parser.get_sed_command()).get_commands()

######################################################
# Handle Cases
######################################################

for command in commands:
    print(command)
